(() => {
"use strict";
if (!window.matchMedia("(max-width: 700px)").matches) return;
const form=document.querySelector(".walk-form");
if(!form||document.querySelector("#outdoorTab"))return;

const style=document.createElement("style");
style.textContent=`
.walk-mode-tabs{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin:0 0 12px;padding:4px;border:2px solid #082e5d;border-radius:14px;background:#dff3f3}
.walk-mode-tabs button{min-height:42px;padding:8px;border:0;border-radius:10px;background:transparent;color:#082e5d;box-shadow:none;font-size:.72rem;font-weight:900}
.walk-mode-tabs button.active{background:#ffd23f;box-shadow:0 3px 0 #d49b16}
.outdoor-walk-panel{padding:13px;border:2px dashed #1597aa;border-radius:15px;background:#f5fffe}.outdoor-walk-panel[hidden]{display:none!important}
.gps-status{display:flex;align-items:center;gap:8px;margin-bottom:10px;color:#173a5e;font-size:.72rem;font-weight:900}.gps-status i{width:10px;height:10px;border-radius:50%;background:#a5aba8}.gps-status.tracking i{background:#16a57d;box-shadow:0 0 0 4px #16a57d28;animation:gpsPulse 1.4s infinite}
.gps-metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin-bottom:11px}.gps-metrics div{padding:9px 4px;border-radius:10px;background:#fff8e8;text-align:center}.gps-metrics span{display:block;color:#66736d;font-size:.58rem;font-weight:900;text-transform:uppercase}.gps-metrics strong{display:block;margin-top:3px;color:#082e5d;font-size:1.02rem}
.gps-controls{display:grid;grid-template-columns:1fr 1fr;gap:7px}.gps-controls button{min-height:42px;padding:8px;font-size:.69rem}.gps-controls .gps-start{grid-column:1/-1;background:#16a57d;box-shadow:0 4px 0 #08745a}.gps-controls .gps-pocket{background:#ffd23f;color:#082e5d;box-shadow:0 4px 0 #d49b16}.gps-controls .gps-stop{background:#f05245;box-shadow:0 4px 0 #a93430}.gps-help{margin:10px 2px 0;color:#66736d;font-size:.64rem;line-height:1.35}
.pocket-lock{position:fixed;z-index:10000;inset:0;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:28px;background:#061f3ef5;color:#fff8e8;text-align:center;touch-action:none;user-select:none}.pocket-lock[hidden]{display:none!important}.pocket-lock .pocket-icon{font-size:3.2rem}.pocket-lock h2{margin:12px 0 4px;font:400 2.1rem/1 "Lobster",Georgia,serif}.pocket-lock p{margin:0 0 24px;color:#bfeaed;font-size:.78rem}.pocket-metrics{display:flex;gap:28px;margin-bottom:38px}.pocket-metrics strong{display:block;font-size:2rem}.pocket-metrics span{font-size:.68rem;text-transform:uppercase}.pocket-unlock{width:190px;height:58px;border:3px solid #ffd23f;border-radius:999px;background:#0b3768;color:#fff;font-weight:900;box-shadow:none!important}.pocket-unlock.holding{background:#f05245}
.gps-summary{width:min(92vw,430px);padding:0;border:0;border-radius:20px;background:#fff8e8;color:#082e5d;box-shadow:0 24px 70px #00152b88}.gps-summary::backdrop{background:#041b36c9}.gps-summary-inner{padding:23px}.gps-summary h2{margin:0 0 5px;font:400 2rem/1 "Lobster",Georgia,serif}.gps-summary p{color:#66736d}.gps-summary-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin:17px 0}.gps-summary-grid div{padding:12px 5px;border-radius:11px;background:#dff3f3;text-align:center}.gps-summary-grid strong{display:block;font-size:1.2rem}.gps-summary-grid span{font-size:.6rem;font-weight:900;text-transform:uppercase}.gps-summary-actions{display:grid;grid-template-columns:.8fr 1.2fr;gap:8px}.gps-summary-actions button{min-height:44px;padding:8px}
@keyframes gpsPulse{50%{box-shadow:0 0 0 9px #16a57d12}}
`;
document.head.appendChild(style);

const tabs=document.createElement("div");
tabs.className="walk-mode-tabs";tabs.innerHTML='<button id="indoorTab" class="active" type="button">🏠 Tapis</button><button id="outdoorTab" type="button">🌿 Marche dehors</button>';
const title=form.querySelector(".section-title");title.insertAdjacentElement("afterend",tabs);
const manual=[...form.children].filter(el=>el!==title&&el!==tabs&&el.id!=="walkAnimation");

const panel=document.createElement("div");panel.className="outdoor-walk-panel";panel.hidden=true;
panel.innerHTML='<div id="gpsStatus" class="gps-status"><i></i><span>GPS prêt à démarrer</span></div><div class="gps-metrics"><div><span>Durée</span><strong id="gpsDuration">00:00</strong></div><div><span>Distance</span><strong id="gpsDistance">0,00 km</strong></div><div><span>Vitesse</span><strong id="gpsSpeed">0,0 km/h</strong></div></div><div class="gps-controls"><button id="gpsStart" class="gps-start" type="button">Démarrer la marche</button><button id="gpsPause" class="secondary" type="button" hidden>Pause</button><button id="gpsPocket" class="gps-pocket" type="button" hidden>Mode poche</button><button id="gpsStop" class="gps-stop" type="button" hidden>Terminer</button></div><p class="gps-help">L’écran restera allumé en mode poche. Le tracé précis n’est ni publié ni ajouté au carnet.</p>';
form.appendChild(panel);

document.body.insertAdjacentHTML("beforeend",'<div id="pocketLock" class="pocket-lock" hidden><div class="pocket-icon">🔒</div><h2>Mode poche actif</h2><p>Les commandes sont protégées et l’écran reste allumé.</p><div class="pocket-metrics"><div><strong id="pocketDuration">00:00</strong><span>Durée</span></div><div><strong id="pocketDistance">0,00 km</strong><span>Distance</span></div></div><button id="pocketUnlock" class="pocket-unlock" type="button">Maintenir 3 secondes</button></div><dialog id="gpsSummary" class="gps-summary"><div class="gps-summary-inner"><h2>Marche terminée !</h2><p>Vérifie les données avant de les ajouter au Tour de Papa.</p><div class="gps-summary-grid"><div><strong id="summaryDuration">0 min</strong><span>Durée</span></div><div><strong id="summaryDistance">0,00 km</strong><span>Distance</span></div><div><strong id="summarySpeed">0,0 km/h</strong><span>Vitesse</span></div></div><div class="gps-summary-actions"><button id="gpsDiscard" class="secondary" type="button">Annuler</button><button id="gpsValidate" type="button">Ajouter au parcours</button></div></div></dialog>');

const $=s=>document.querySelector(s),state={watch:null,running:false,paused:false,last:null,meters:0,start:0,elapsed:0,timer:null,wake:null},draftKey="tdfPapaOutdoorDraft";
const elapsed=()=>state.elapsed+(state.running&&!state.paused?Date.now()-state.start:0),km=()=>state.meters/1000,speed=()=>elapsed()?km()/(elapsed()/3600000):0,clock=ms=>{const s=Math.floor(ms/1000);return String(Math.floor(s/60)).padStart(2,"0")+":"+String(s%60).padStart(2,"0")};
function renderGps(){const d=clock(elapsed()),k=km().toLocaleString("fr-FR",{minimumFractionDigits:2,maximumFractionDigits:2})+" km",v=speed().toLocaleString("fr-FR",{minimumFractionDigits:1,maximumFractionDigits:1})+" km/h";$("#gpsDuration").textContent=d;$("#gpsDistance").textContent=k;$("#gpsSpeed").textContent=v;$("#pocketDuration").textContent=d;$("#pocketDistance").textContent=k}
function draft(){if(state.running)localStorage.setItem(draftKey,JSON.stringify({meters:state.meters,elapsed:elapsed()}))}
function hav(a,b){const R=6371000,r=x=>x*Math.PI/180,d1=r(b.lat-a.lat),d2=r(b.lon-a.lon),q=Math.sin(d1/2)**2+Math.cos(r(a.lat))*Math.cos(r(b.lat))*Math.sin(d2/2)**2;return 2*R*Math.atan2(Math.sqrt(q),Math.sqrt(1-q))}
function position(p){const n={lat:p.coords.latitude,lon:p.coords.longitude,t:p.timestamp||Date.now(),accuracy:p.coords.accuracy||999};$("#gpsStatus").classList.add("tracking");$("#gpsStatus span").textContent="GPS actif · précision "+Math.round(n.accuracy)+" m";if(n.accuracy>60)return;if(state.last){const segment=hav(state.last,n),secs=Math.max(1,(n.t-state.last.t)/1000);if(segment>=2&&segment/secs*3.6<=14)state.meters+=segment}state.last=n;draft();renderGps()}
function gpsError(e){const m={1:"Autorise la position GPS pour démarrer.",2:"Signal GPS indisponible.",3:"Le GPS met trop de temps à répondre."};$("#gpsStatus").classList.remove("tracking");$("#gpsStatus span").textContent=m[e.code]||"Impossible d’utiliser le GPS."}
function watch(){if(!navigator.geolocation)return alert("Le GPS n’est pas disponible.");state.watch=navigator.geolocation.watchPosition(position,gpsError,{enableHighAccuracy:true,maximumAge:2000,timeout:15000})}
async function wake(){try{if("wakeLock"in navigator&&!state.wake)state.wake=await navigator.wakeLock.request("screen")}catch(_){}}
function start(){state.running=true;state.paused=false;state.start=Date.now();state.last=null;$("#gpsStart").hidden=true;$("#gpsPause").hidden=false;$("#gpsPocket").hidden=false;$("#gpsStop").hidden=false;$("#gpsPause").textContent="Pause";$("#gpsStatus span").textContent="Recherche du signal GPS…";watch();wake();clearInterval(state.timer);state.timer=setInterval(()=>{renderGps();draft()},1000)}
function pause(){if(!state.paused){state.elapsed=elapsed();state.paused=true;state.last=null;if(state.watch!==null)navigator.geolocation.clearWatch(state.watch);state.watch=null;$("#gpsPause").textContent="Reprendre";$("#gpsStatus").classList.remove("tracking");$("#gpsStatus span").textContent="Marche en pause"}else{state.paused=false;state.start=Date.now();$("#gpsPause").textContent="Pause";watch()}draft();renderGps()}
function finish(){if(!state.running)return;if(!state.paused)state.elapsed=elapsed();state.running=false;state.paused=true;if(state.watch!==null)navigator.geolocation.clearWatch(state.watch);clearInterval(state.timer);state.wake?.release().catch(()=>{});$("#pocketLock").hidden=true;$("#summaryDuration").textContent=Math.max(1,Math.round(state.elapsed/60000))+" min";$("#summaryDistance").textContent=km().toLocaleString("fr-FR",{minimumFractionDigits:2,maximumFractionDigits:2})+" km";$("#summarySpeed").textContent=speed().toLocaleString("fr-FR",{minimumFractionDigits:1,maximumFractionDigits:1})+" km/h";$("#gpsSummary").showModal()}
function reset(){localStorage.removeItem(draftKey);Object.assign(state,{watch:null,running:false,paused:false,last:null,meters:0,start:0,elapsed:0,timer:null,wake:null});$("#gpsStart").hidden=false;$("#gpsPause").hidden=true;$("#gpsPocket").hidden=true;$("#gpsStop").hidden=true;$("#gpsStatus").classList.remove("tracking");$("#gpsStatus span").textContent="GPS prêt à démarrer";renderGps()}
async function validate(){const distance=Math.round(km()*100)/100,duration=Math.max(1,Math.round(state.elapsed/60000));if(distance<=0)return alert("Aucune distance GPS exploitable n’a été mesurée.");if(distance>30)return alert("Cette marche dépasse 30 km.");const from=totalDistance(),before=currentStageFor(from),avg=Math.round(distance/(duration/60)*100)/100;data.walks.push({date:new Date().toLocaleDateString("fr-FR"),session:"Marche dehors",duration,distance,heartRate:"",incline:0,speed:avg,source:"GPS"});save();$("#gpsSummary").close();reset();animationRunning=true;try{await animateWalk(from,totalDistance(),(data.walks.length-1)%papaActions.length)}finally{animationRunning=false;render()}const after=currentStageFor(totalDistance());if(after>before)celebrate(after)}
function mode(out){$("#indoorTab").classList.toggle("active",!out);$("#outdoorTab").classList.toggle("active",out);manual.forEach(el=>el.hidden=out);panel.hidden=!out}
$("#indoorTab").onclick=()=>mode(false);$("#outdoorTab").onclick=()=>mode(true);$("#gpsStart").onclick=start;$("#gpsPause").onclick=pause;$("#gpsStop").onclick=finish;$("#gpsPocket").onclick=()=>{wake();$("#pocketLock").hidden=false;document.documentElement.requestFullscreen?.().catch(()=>{})};$("#gpsDiscard").onclick=()=>{$("#gpsSummary").close();reset()};$("#gpsValidate").onclick=validate;
let hold;const unlock=$("#pocketUnlock");const cancel=()=>{clearTimeout(hold);unlock.classList.remove("holding")};unlock.onpointerdown=()=>{cancel();unlock.classList.add("holding");hold=setTimeout(()=>{$("#pocketLock").hidden=true;unlock.classList.remove("holding");document.exitFullscreen?.().catch(()=>{})},3000)};["pointerup","pointercancel","pointerleave"].forEach(e=>unlock.addEventListener(e,cancel));
document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible"&&state.running)wake()});
try{const d=JSON.parse(localStorage.getItem(draftKey)||"null");if(d&&d.elapsed){state.meters=Number(d.meters)||0;state.elapsed=Number(d.elapsed)||0;$("#gpsStatus span").textContent="Marche interrompue récupérée";$("#gpsStart").textContent="Reprendre la marche";renderGps()}}catch(_){}
})();